# Generated by Django 5.0 on 2023-12-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_staff2',
            field=models.BooleanField(default=False),
        ),
    ]
