# Generated by Django 5.0 on 2023-12-27 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_is_active_useraccount_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='first_name',
            field=models.CharField(default='denis', max_length=30),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='last_name',
            field=models.CharField(default='tosa', max_length=30),
        ),
    ]
