# Generated by Django 5.0 on 2024-01-20 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_useraccount_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'permissions': (('baseuser', 'baseuser'), ('vipuser', 'vipuser'))},
        ),
    ]
