# Generated by Django 5.0 on 2024-01-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_useraccount_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
